### PR TITLE
Add Chinese

### PR DESCRIPTION
**Pull request by p1ao12138**

### CODE REVIEW

**Comment by DarkGuardsman** [comment]
@bl4ckscor3 do you know a good way to validate this?

**Comment by bl4ckscor3** [comment]
No. I usually just translate a couple randomly chosen lines to see if they make sense, then assume the rest is fine as well.

**Comment by DarkGuardsman** [comment]
Looks good, sorry for the delay forgot about the MR

**Comment by DarkGuardsman** [comment]
> No. I usually just translate a couple randomly chosen lines to see if they make sense, then assume the rest is fine as well.

Yep, put the whole file into translate and did a quick check. I might automate this later using the google API to give us a bot green check in the MR.

**Pull request merged**
